-- Generated by tools/import-dc-comics.sh
-- Run this after Database/seed.sql if you want the downloaded DC comics in your local database.

INSERT INTO "Comics"
("Id", "SeriesName", "VolumeNumber", "IssueNumber", "Title", "Author", "Genre", "SecondaryGenre", "Description", "CoverImagePath", "PdfPath", "IsIReadPick")
VALUES
(2001, 'Batman', 1, 1, 'Batman Vol. 1 Issue 1', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_1_COVER.jpg', '', false),
(2002, 'Batman', 1, 2, 'Batman Vol. 1 Issue 2', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_2_COVER.jpg', '', false),
(2003, 'Batman', 1, 3, 'Batman Vol. 1 Issue 3', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_3_COVER.jpg', '', false),
(2006, 'Batman', 1, 6, 'Batman Vol. 1 Issue 6', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_6_COVER.jpg', '', false),
(2007, 'Batman', 1, 7, 'Batman Vol. 1 Issue 7', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_7_COVER.jpg', '', false),
(2008, 'Batman', 1, 8, 'Batman Vol. 1 Issue 8', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_8_COVER.jpg', '', false),
(2010, 'Batman', 1, 10, 'Batman Vol. 1 Issue 10', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_10_COVER.jpg', '', false),
(2012, 'Batman', 1, 12, 'Batman Vol. 1 Issue 12', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_12_COVER.jpg', '', false),
(2022, 'Batman', 1, 22, 'Batman Vol. 1 Issue 22', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_22_COVER.jpg', '', false),
(2025, 'Batman', 1, 25, 'Batman Vol. 1 Issue 25', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_25_COVER.jpg', '', false),
(2031, 'Batman', 1, 31, 'Batman Vol. 1 Issue 31', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_31_COVER.jpg', '', false),
(2033, 'Batman', 1, 33, 'Batman Vol. 1 Issue 33', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_33_COVER.jpg', '', false),
(2034, 'Batman', 1, 34, 'Batman Vol. 1 Issue 34', 'DC Comics', 'Action', 'Classic', 'A classic DC Comics issue from the Batman series.', '/images/covers/dc/batman_vol1_issue_34_COVER.jpg', '', false),
(3002, 'Men of War', 1, 2, 'Men of War Vol. 1 Issue 2', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_2_COVER.jpg', '', false),
(3005, 'Men of War', 1, 5, 'Men of War Vol. 1 Issue 5', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_5_COVER.jpg', '', false),
(3006, 'Men of War', 1, 6, 'Men of War Vol. 1 Issue 6', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_6_COVER.jpg', '', false),
(3007, 'Men of War', 1, 7, 'Men of War Vol. 1 Issue 7', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_7_COVER.jpg', '', false),
(3008, 'Men of War', 1, 8, 'Men of War Vol. 1 Issue 8', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_8_COVER.jpg', '', false),
(3011, 'Men of War', 1, 11, 'Men of War Vol. 1 Issue 11', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_11_COVER.jpg', '', false),
(3012, 'Men of War', 1, 12, 'Men of War Vol. 1 Issue 12', 'DC Comics', 'War', 'Military', 'A vintage DC war comic from the Men of War series.', '/images/covers/dc/men_of_war_vol1_issue_12_COVER.jpg', '', false)
ON CONFLICT ("Id") DO UPDATE SET
    "SeriesName" = EXCLUDED."SeriesName",
    "VolumeNumber" = EXCLUDED."VolumeNumber",
    "IssueNumber" = EXCLUDED."IssueNumber",
    "Title" = EXCLUDED."Title",
    "Author" = EXCLUDED."Author",
    "Genre" = EXCLUDED."Genre",
    "SecondaryGenre" = EXCLUDED."SecondaryGenre",
    "Description" = EXCLUDED."Description",
    "CoverImagePath" = EXCLUDED."CoverImagePath",
    "PdfPath" = EXCLUDED."PdfPath",
    "IsIReadPick" = EXCLUDED."IsIReadPick";
