<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;bin\**\*;obj\**;obj\**\*;**/BuildHost-net472/**;**/BuildHost-netcore/**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="bin\**;bin\**\*;obj\**;obj\**\*;**/BuildHost-net472/**;**/BuildHost-netcore/**" />
        <Content Remove="bin\**;bin\**\*;obj\**;obj\**\*;**/BuildHost-net472/**;**/BuildHost-netcore/**" />
        <EmbeddedResource Remove="bin\**;bin\**\*;obj\**;obj\**\*;**/BuildHost-net472/**;**/BuildHost-netcore/**" />
        <None Remove="bin\**;bin\**\*;obj\**;obj\**\*;**/BuildHost-net472/**;**/BuildHost-netcore/**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0" />
    </ItemGroup>

</Project>
