#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
downloads_root="${1:-/Users/alexandrafomina/Downloads}"
archive_root="$repo_root/Project498.WebServer/wwwroot/comic-archives"
cover_root="$repo_root/Project498.WebServer/wwwroot/images/covers/dc"
sql_path="$repo_root/Project498.WebApi/Database/dc-comics.seed.sql"

mkdir -p "$archive_root" "$cover_root"

ln -sfn "$downloads_root/batman-1-100" "$archive_root/batman-1-100"
ln -sfn "$downloads_root/men-of-war-part-1" "$archive_root/men-of-war-part-1"

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

slugify() {
  printf "%s" "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//'
}

first_image_from_archive() {
  local archive="$1"
  bsdtar -tf "$archive" \
    | grep -Ei '\.(jpg|jpeg|png|webp)$' \
    | sort -f \
    | head -n 1
}

cover_for_archive() {
  local archive="$1"
  local cover_file="$2"

  if [ -f "$cover_file" ]; then
    return
  fi

  local first_image
  first_image="$(first_image_from_archive "$archive")"
  if [ -z "$first_image" ]; then
    return
  fi

  bsdtar -xOf "$archive" "$first_image" > "$cover_file"
}

cover_for_pdf() {
  local pdf="$1"
  local cover_file="$2"

  if [ -f "$cover_file" ]; then
    return
  fi

  local tmp_dir
  tmp_dir="$(mktemp -d)"
  qlmanage -t -s 900 -o "$tmp_dir" "$pdf" >/dev/null 2>&1 || true

  local generated
  generated="$(find "$tmp_dir" -type f -name '*.png' | head -n 1)"
  if [ -n "$generated" ]; then
    cp "$generated" "$cover_file"
  fi

  rm -rf "$tmp_dir"
}

selected_file="$(mktemp)"
cleanup_selected_file() {
  rm -f "$selected_file"
}
trap cleanup_selected_file EXIT

: > "$selected_file"

while IFS= read -r file; do
  base="$(basename "$file")"
  if [[ "$base" =~ Batman[[:space:]]+0*([0-9]{1,3}) ]]; then
    issue="${BASH_REMATCH[1]}"
    key="Batman:$issue"

    if ! grep -Fq "$key|" "$selected_file"; then
      echo "$key|$file" >> "$selected_file"
    fi
  fi
done < <(find "$downloads_root/batman-1-100" -maxdepth 1 -type f -iname '*.cbz' | sort)

while IFS= read -r file; do
  base="$(basename "$file")"
  if [[ "$base" =~ Men[[:space:]]+[Oo]f[[:space:]]+War[[:space:]]+0*([0-9]{1,3}) ]]; then
    issue="${BASH_REMATCH[1]}"
    key="Men of War:$issue"

    if ! grep -Fq "$key|" "$selected_file"; then
      echo "$key|$file" >> "$selected_file"
    fi
  fi
done < <(find "$downloads_root/men-of-war-part-1" -maxdepth 1 -type f -iname '*.cbz' | sort)

{
  echo "-- Generated by tools/import-dc-comics.sh"
  echo "-- Run this after Database/seed.sql if you want the downloaded DC comics in your local database."
  echo
  echo "INSERT INTO \"Comics\""
  echo "(\"Id\", \"SeriesName\", \"VolumeNumber\", \"IssueNumber\", \"Title\", \"Author\", \"Genre\", \"SecondaryGenre\", \"Description\", \"CoverImagePath\", \"PdfPath\", \"IsIReadPick\")"
  echo "VALUES"
} > "$sql_path"

first_row=true

row_count=0
ordered_keys="$(
  {
    cut -d'|' -f1 "$selected_file" | grep '^Batman:' | sort -t: -k2,2n | head -n 13
    cut -d'|' -f1 "$selected_file" | grep '^Men of War:' | sort -t: -k2,2n | head -n 7
  }
)"

while IFS= read -r key; do
  if [ -z "$key" ]; then
    continue
  fi

  series="${key%%:*}"
  issue="${key##*:}"
  file="$(grep -F "$key|" "$selected_file" | head -n 1 | cut -d'|' -f2-)"
  base="$(basename "$file")"
  slug="$(slugify "${series}_vol1_issue_${issue}")"
  cover_file="$cover_root/${slug}_COVER.jpg"
  cover_path="/images/covers/dc/${slug}_COVER.jpg"

  if [[ "$file" == *.pdf ]]; then
    cover_file="$cover_root/${slug}_COVER.png"
    cover_path="/images/covers/dc/${slug}_COVER.png"
    static_path="/comics/$(basename "$file")"
    cp -f "$file" "$repo_root/Project498.WebServer/wwwroot/comics/$(basename "$file")"
    cover_for_pdf "$file" "$cover_file"
  elif [[ "$series" == "Batman" ]]; then
    static_path="/comic-archives/batman-1-100/$base"
    cover_for_archive "$file" "$cover_file"
  else
    if [[ "$file" == *.cbr ]]; then
      generated_cbz_dir="$archive_root/generated-cbz"
      mkdir -p "$generated_cbz_dir"
      generated_cbz="$generated_cbz_dir/${slug}.cbz"
      convert_cbr_to_cbz "$file" "$generated_cbz"
      static_path="/comic-archives/generated-cbz/${slug}.cbz"
    else
      static_path="/comic-archives/men-of-war-part-1/$base"
    fi

    cover_for_archive "$file" "$cover_file"
  fi

  title="$series Vol. 1 Issue $issue"
  genre="Action"
  secondary_genre="Classic"
  description="A classic DC Comics issue from the $series series."

  if [[ "$series" == "Men of War" ]]; then
    genre="War"
    secondary_genre="Military"
    description="A vintage DC war comic from the Men of War series."
  fi

  id=$((2000 + issue))
  if [[ "$series" == "Men of War" ]]; then
    id=$((3000 + issue))
  fi

  if [ "$first_row" = false ]; then
    echo "," >> "$sql_path"
  fi

  printf "(%s, '%s', 1, %s, '%s', 'DC Comics', '%s', '%s', '%s', '%s', '%s', false)" \
    "$id" \
    "$(sql_escape "$series")" \
    "$issue" \
    "$(sql_escape "$title")" \
    "$(sql_escape "$genre")" \
    "$(sql_escape "$secondary_genre")" \
    "$(sql_escape "$description")" \
    "$(sql_escape "$cover_path")" \
    "$(sql_escape "$static_path")" >> "$sql_path"

  first_row=false
  row_count=$((row_count + 1))
done <<< "$ordered_keys"

echo >> "$sql_path"
cat >> "$sql_path" <<'SQL'
ON CONFLICT ("Id") DO UPDATE SET
    "SeriesName" = EXCLUDED."SeriesName",
    "VolumeNumber" = EXCLUDED."VolumeNumber",
    "IssueNumber" = EXCLUDED."IssueNumber",
    "Title" = EXCLUDED."Title",
    "Author" = EXCLUDED."Author",
    "Genre" = EXCLUDED."Genre",
    "SecondaryGenre" = EXCLUDED."SecondaryGenre",
    "Description" = EXCLUDED."Description",
    "CoverImagePath" = EXCLUDED."CoverImagePath",
    "PdfPath" = EXCLUDED."PdfPath",
    "IsIReadPick" = EXCLUDED."IsIReadPick";
SQL
echo "Generated $sql_path"
echo "Included $row_count DC comics."
